### PR TITLE
Compilify

### LINKED ISSUE #21: Validate bit ranges for fields.
Hi there, thanks for the great crate.
I propose adding validation functionality for the field definitions so that the specified bit-ranges cover exactly all specified register `SIZE_BITS` and so that they do not overlap. Currently, a bit-range can be out of bounds and the macro does not catch it.

### LINKED ISSUE #29: Per field R/W permission
Right now we can specify for each register whether it can be read, written and cleared. Before the big rewrite this was also possible per field and we lost that ability. Would be nice to get that back.

### LINKED ISSUE #30: Global setting for endianness and bitorder
We can set the endianness per register. But the default is always big-endian. Would be nice to have the ability to change the default.
Same with bitorder, but that can't be controlled at all right now.

This all comes a cost though since it makes the bits way more complex and it's not always clear how the documentation of a chip defines the endianness and bitorder

### LINKED ISSUE #31: Repeat for registers
The repeat feature has been added to register blocks, but not yet for standalone registers

### LINKED ISSUE #33: Extend the 'command device' to support more complex devices
Hi! I like this crate a lot, and have used it to implement some drivers for devices that work with registers.

However, I now wanted to use it to write a driver for this device: [MLX90393](https://www.melexis.com/en/documents/documentation/datasheets/datasheet-mlx90393). Reading the datasheet it would probably be modeled as a 'command device' where the commands can have arguments and return information, but that type of command does not seem to be possible with `device-driver`.

I'll try modeling the device as a register device, and see if that works. How would you model this device? Does it make sense to expand the 'command device' to accommodate more complex commands?

Thanks

### LINKED ISSUE #34: Rethinking this crate and structure
We're running into some problems:

- DLS parsing is overly strict
  - Try changing the order of the consts and types
- User errors can be better
- Processing of data is done in many different places and needs streamlining
- Some features are implemented in some cases and are missing in other
- Commands need an overhaul to be able to carry data and return values

I think all these issues stem from the fact that this crate is really a compiler, but isn't structured as a compiler.
It doesn't help that this was my first big proc macro I wrote.

So the solution? Make it look more like a compiler. Something like this:
```
                                                       Close to textual/           Check for correct         Fully formed types         Straighten data            The exact, correct                                                                                      
                                                       token input with            keywords in right         but not yet type           to make it easy to         data we're gonna                                                                                        
                                                       little validation           places and no             checked and things         generate output            generate code from                                                                                      
                                                                                   duplicates                may be wrong               from                                                                                                                               
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                           
┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐                             
│                    │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │                             
│ DSL                │     │ Parsing with       │     │ Syn-based HIR      │     │ Syntax             │     │ MIR                │     │ Semantics checking │     │ LIR                │     │ 'quote' generation │     │ Tokenstream        │                             
│ Macro              ├─────► Syn                ├─────►                    ├─────► Checking           ├─────►                    ├─────► and resolving links├─────►                    ├─────►                    ├─────► Output             │                             
│ Tokens             │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │     │                    │                             
└────────────────────┘     └────────────────────┘     └────────────────────┘     └────────────────────┘     └─────────▲──────────┘     └────────────────────┘     └────────────────────┘     └────────────────────┘     └────────────────────┘                             
                                                                                                                      │                                                                                                                                                    
┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐     ┌────────────────────┐               │                                                                                                                                                    
│                    │     │                    │     │                    │     │                    │               │                                                                                                                                                    
│ Json               │     │ Parsing with       │     │ Serde-based HIR    │     │ Syntax             │               │                                                                                                                                                    
│ Text               ├─────► serde-json         ├─────►                    ├─────► Checking           ├───────────────┘                                                                                                                                                    
│                    │     │                    │     │                    │     │                    │                                                                                                                                                                    
└────────────────────┘     └────────────────────┘     │                    │     └────────────────────┘                                                                                                                                                                    
                                                      │                    │                                                                                                                                                                                               
┌────────────────────┐     ┌────────────────────┐     │                    │                                                                                                                                                                                               
│                    │     │                    │     │                    │                                                                                                                                                                                               
│ Yaml               │     │ Parsing with       │     │                    │                                                                                                                                                                                               
│ Text               ├─────► serde-yaml         ├─────►                    │                                                                                                                                                                                               
│                    │     │                    │     │                    │                                                                                                                                                                                               
└────────────────────┘     └────────────────────┘     └────────────────────┘                                                                                                                                                                                               
```

Maybe the two HIRs can be collapsed into one? I don't know.

This should hopefully unlock more easy options for building new features and sharing features between different parts.

One other reason for this change is that the commands need expanding.
Commands right now are just a single command. It doesn't carry data and it can't return anything.
It would be awesome if we could reuse the field logic of the registers.

Blocks right now cannot carry commands or buffers or other blocks.

Registers cannot be repeated now.

So many things...

### LINKED ISSUE #35: More control over case conversions?
Right now converting names from pascal case to snake case can lead to some undesirable word boundaries. For example `I2cSettings` turns into `i_2_c_settings` in snake case and `I2CSettings` (note the capital `C`) in pascal case. I'm not sure what the best solution would be to give the user more control over those conversions. One option would be to use an unambiguous casing as the input in all cases (such as snake case). Another option would be to let the user optionally specify the casings somehow.

I would consider this a pretty minor issue, but something worth thinking about; particularly if you move forward with something like #34.

### LINKED ISSUE #42: Allow reset value override on register refs
This was added in the compilify branch but then later removed because it was not used. It needs a refactor to be added again.

It was removed in: https://github.com/diondokter/device-driver/pull/40/commits/15fcfa23bb125247d542cf91f21dd3c1c9fe2ced

### PR DESCRIPTION
**Pull request by diondokter**
Complete rebuild.

Closes #42 
Closes #35
Closes #34  
Closes #33 
Closes #31 
Closes #30 
Closes #29
Closes #21

Posting this since we're nearing finishing.

Todo:

- [x] Restructure as a compiler
- [x] Better name normalization
- [x] Address overlap checks
- [x] Field overlap checks
- [x] Commands can have fields
- [x] Per field access setting
- [x] Better enum generation
- [x] Nicer type conversion
- [x] Redo field writer struct generation
- [x] Add bit manip traits to field writer struct
- [x] Add blocks for everything
- [x] Add refs for everything
- [x] Add repeat for everything (except buffers)
- [x] Fix byte order
- [x] Add global byte order and bit order config
- [x] Add global register, command and buffer address type config
- [x] Writing more high level tests
- [x] Add check for whether all addresses fit in in given address types
- [x] Write book-like docs (tutorial?)
- [x] Add json support
- [x] Add yaml support
- [x] Add toml support
- [x] Add dsl from file support
- [x] Add cli to support `include!` usecases
- [x] Update readme
- [x] Split out changelog from readme
- [x] Change CI to only push book on master

### CODE REVIEW

**Comment by alexmoon** [comment]
Gave this a try with my device implementation, but ran into a few issues:
- I have a few registers that are different based on cfg attributes:
  ```
  #[cfg(feature = "foo")]
  register Foo { ... }
  #[cfg(not(feature = "foo"))]
  register Foo { ... }
  ```
  This causes a `Duplicate object name found: "Foo"` error.
- Similarly I have some blocks that have registers with the same name:
  ```
  block SensorSetup {
    ...
    register Setup { ... }
  }
  block ChannelSetup {
    ...
    register Setup { ... }
  }
  ```
  This causes the same error. I'd like to have the register names namespaced by their blocks so I don't have to have overly long names.
- I have a register with a boolean flags:
  ```
  register Foo {
    foo: bool = 0,
    bar: bool = 1,
    baz: bool = 2,
  }
  ```
  This is causing a `Object "Foo" has field "foo" that is 0 bits. This is likely a mistake.` (and same for the other fields if the earlier fields are commented out). I would like boolean fields to default to 1 bit wide like in the current version.

**Comment by diondokter** [comment]
Hey cool, thanks for trying it out @alexmoon!

The first one would be a good test to add. I see what's going on and will be difficult to fix. There's a pass to make sure all names are unique. However that doesn't take into account the cfg. And I can't really look at the cfg because that only has meaning when the driver itself is compiling... Not sure what I can do about that... Maybe if a there's a name collision we can let it slide if both have a cfg? I'd have to check what happens with a ref object that refs one of the two...

The last one I thought should work... If it doesn't that's indeed a mistake yeah!
I think it's here: https://github.com/diondokter/device-driver/blob/5db85da3d87dee67084b3c256f9e59ee342b3666/generation/src/mir/passes/bit_ranges_validated.rs#L45-L49
So yeah, I added logic to bools so they are accepted as 0-bits, but probably I should transform them to be one bit. Good catch!
Gonna add a test for that too.

Your middle one is a bit more difficult. I would like that to work but I made the decision to have all names be unique. Because if they don't have to be, then that'd open a giant can of worms.
- For duplicate names in different blocks, what's gonna be the generated name used in the code?
  - Make blocks generate modules and put all sub items in that mod?
    - That'd be a giant PITA in the LIR<>token transform
  - Prepend the block name in front of the generated type?
    - What if we are 4 blocks deep? 4 names prepended? Doesn't sound great...
- How do we ref an object that is in a different block?
  - Should we forbid it? This limits what a user can do
  - Add syntax so you specify a path? This is technically challenging

For now I think I'm gonna keep the uniqueness of names constraint. This can later be relaxed to support your usecase by putting generated code in modules and adding paths for reffing objects. Right now this is already a huge PR and I want to merge it before I add more complexity like this. Hope you understand! It's a bit annoying for now.

**Comment by diondokter** [comment]
^^^

Zero-bit bools are fixed now

**Comment by diondokter** [comment]
^^^

@alexmoon Your first point is now fixed too. This can cause errors in the generated code now which is not ideal. I'd like to catch it in the macro itself. But the errors aren't too bad and when you're touching cfgs and stuff stops compiling, it's quite obvious what's going on.

For ref objects everything also turns out fine. It uses whichever type ends up being active.

**Comment by alexmoon** [comment]
Those fixes work for me! I can live with the unique names, I think it was a little nicer with having each block in its own module, but this solution is simpler.

Overall I think the new DSL is a definite improvement. The error checking is great and not having to repeat things like byte order and address type over and over again makes it cleaner.

Having the interface separate from the root register block felt a little weird. I like the simplicity it adds for the code generation, but for a driver crate I want to present a single type to my users rather than exposing two. My solution for this was to expose just the interface struct, but impl the `RegisterInterface` trait on a `&mut Interface` and add a `regs()` method to the interface struct which constructs the root register block on demand.

In my case having the regs a layer deeper in the API actually feels kind of nice, but some drivers may want to have the registers right on the top level struct. If there was a way to suppress or override the constructor generation, you could potentially keep the interface struct mostly hidden from end users, but it would still appear in the type of the struct.

I did have to set `ALLOW_ADDRESS_OVERLAP` on my `cfg`ed registers which was a little surprising, but understandable.

It would be nice if the `RESET_VALUE` could accept `cfg` attributes. Several of my duplicated registers are just due to needing a different `RESET_VALUE` depending on the feature selected.

Having to write `set_...` for every method when writing a register is slightly annoying, but I think the simplicity of a single struct per register is more than worth it.

It would be nice for the register structs to have a constructor (or impl `Default`) so that you can pre-configure a register before writing to the device. I've worked around this for now by using the `From<[u8; N]>` impl. I wonder if it would make sense to also have `From<u??>` and `From<Reg> for u??` impls where the register is exactly 8, 16, 32, or 64 bits wide?

It would also be great if the register constructor and methods could be `const` so that you could store a register configuration in a `const` or `static`, but I don't think that's possible since the underlying bitvec methods are non-`const`.

**Comment by alexmoon** [comment]
A couple of other thoughts:

Another way to deal with the interface/root block split would be to use the interface as the exported type from a driver crate, but then `impl DerefMut` on it to the root block. That would effectively make all the register methods available on the interface struct. The docs would still be split between the two structs, but otherwise I think that would work pretty well.

Regarding constructing registers, it might also be a good idea to change the `write` and `modify` methods to operate on values instead of mutable references. I expect the vast majority of registers to be 32 bits or less which should be more efficient to handle by value, and for large registers the optimizer might still be able to inline the closure. In my application I need to modify a register, but save the old value. Then do some work. Then restore the previous value. Right now I have to do `device.register().write(|w| { w.clone_from(saved_value); w })` which is kind of gross. If write worked on values instead it would just be `device.register().write(|_| saved_value)`.

**Comment by diondokter** [comment]
> Overall I think the new DSL is a definite improvement. The error checking is great and not having to repeat things like byte order and address type over and over again makes it cleaner.

Thanks!

> Having the interface separate from the root register block felt a little weird.

I can get that. I has a couple of upsides though.
1. This is a pattern that is often used when more than 1 different interface types are supported, like both spi and I2c. So it's no uncommon to see this in drivers already (for example for the lis3dh crate).
2. I also always thought it was weird the macro changed the type you have it. IMO, it's a weird thing that was never explained anywhere.
3. Like you note, having a split between the high level and low level parts of the driver is nice. This makes it more easy and obvious to structure it that way.
4. I really want to have a CLI with which the code can be generated ahead of time that can then be `include!`d. This was not possible with the old setup due to macro hygiene.

> I did have to set ALLOW_ADDRESS_OVERLAP on my cfged registers

Ah yeah, makes sense. I should probably add a chapter on cfg to the book to spell out what the rules are.

> It would be nice if the RESET_VALUE could accept cfg attributes.

Agreed! This was planned to. I made an issue for now. I'd have to restructure a couple of things, but I first want to land this as is.

> Having to write set_... for every method when writing a register is slightly annoying

This mimics the stm32-metapack/chiptool api, which is why I changed it. So it's not new. What I had was a unique combination of things and judged it to be better if I followed an existing thing. Having one type makes things easier in practice too.

> It would be nice for the register structs to have a constructor (or impl Default)

They already exist! But they're private now. I get your desire... However, my idea on how I can add the reset value override for refs depends on the types no knowing their own default value since there may be multiple default values... So not sure how to do this where I can support both features. Maybe a constructor for every use of the type, so one plus one for every ref?

They can't be const sadly because the bitvec functions aren't const. https://github.com/diondokter/device-driver/blob/15fcfa23bb125247d542cf91f21dd3c1c9fe2ced/generation/src/lir/token_transform/field_set_transform.rs#L108-L123
I think I only need [this](https://docs.rs/bitvec/latest/bitvec/array/struct.BitArray.html#method.new) to be const to be able to make mine be const. It's possible I could make it const by not using new and construct it manually... I'd have to try that out.
But the 'what even is the reset value in the presence of overrides?' question still stands.
Having multiple constructors would also be complicated more if there was namespacing in the object names.

> but then impl DerefMut on it to the root block.

That's possible. But that trait is really only meant for things like smart pointers. Personally I like to have a `.ll()` function that returns the object with the registers on it. But you're free to do here as you like.

> it might also be a good idea to change the write and modify methods to operate on values instead of mutable references.

Maybe! I see your point. It probably won't matter for the code optimization. Svd2rust uses the mutable reference like I do now. Embassy does this: https://docs.embassy.dev/stm32-metapac/git/stm32c011d6/common/struct.Reg.html#method.modify

If anything I would follow either one of them. I could change it to be like embassy... Idk... Maybe I should do a poll to see what most people like best.

In any case, thanks for the feedback! You've been really helpful

**Comment by alexmoon** [comment]
> They already exist! But they're private now. I get your desire... However, my idea on how I can add the reset value override for refs depends on the types no knowing their own default value since there may be multiple default values... So not sure how to do this where I can support both features. Maybe a constructor for every use of the type, so one plus one for every ref?

In my specific case, the reset value is determined by cfg features, so it is still compile-time constant and would work with a single constructor. In the more general case that might not work.

> Maybe! I see your point. It probably won't matter for the code optimization. Svd2rust uses the mutable reference like I do now. Embassy does this: https://docs.embassy.dev/stm32-metapac/git/stm32c011d6/common/struct.Reg.html#method.modify
> 
> If anything I would follow either one of them. I could change it to be like embassy... Idk... Maybe I should do a poll to see what most people like best.

I think I would slightly prefer the Embassy version. In the current version, it seems odd to me that you have to return the mutable reference that is passed in, when you really can't return anything else due to lifetimes (unless it is `'static`).  With Embassy's version you can use the return type to get data back out. For example, I could:

```
let prev = dev.reg().modify(|val| core::mem::replace(val, new_value));
...
dev.reg().write(|val| *val = prev);
```

**Comment by diondokter** [comment]
Ok, you've convinced me. It now has the chiptool interface.
Also there are now two constructors for the default value and the zero value.

I think I might be able to do something with with ref reset value overrides. Basically make an extra constructor for every ref that contains its reset value. Then I need to let the RegisterOperation know which constructor to use.

**Comment by diondokter** [comment]
Alright fine. I've implemented reset value overrides on register refs.

The RegisterOperation now takes a function pointer to the correct constructor.
I was worried this would be bad, but the pointer call gets fully inlined!
I love Rustc and LLVM 😄

**Comment by alexmoon** [comment]
Sounds good.

I am getting a panic when I include commit d294039: ``called `Option::unwrap()` on a `None` value``

It seems to be related to having two registers with the same name but different `cfg` settings inside a `block`.

**Comment by diondokter** [comment]
Alright, got caught again by assuming names are unique.
I've now added a proper unique ID type so hopefully that won't happen again.
I've also bulked up the cfg processing a bit.
Hopefully it now works!

**Comment by alexmoon** [comment]
Yep, that works! Thanks!

**Comment by diondokter** [comment]
Ok, let's just merge it. More testing needed though!

**Pull request merged**
